### ISSUE TITLE
"Insert donation form" button not showing on WP 5.6 and Divi theme

### ISSUE THREAD

**Issue by phil8900** [grueneschweiz/wp-raisenow-community-plugin#2]
I am not completely sure what the issue is, but after adding our RaiseNow API Key in the settings I was expecting to see the "Insert donation form" button next to the "Add media" button.

![screen2](https://user-images.githubusercontent.com/4629567/101621623-4a967d00-3a16-11eb-8edb-08f8b5b39080.png)Ins
![screen1](https://user-images.githubusercontent.com/4629567/101621626-4b2f1380-3a16-11eb-9121-63b7b58605a0.png)

Is there a way how I could check if the plugin is working properly on my site?

Thanks & best regards,
Philip

**Comment by cyrillbolliger** [comment]
Since the Divi theme is not FOSS, I'm not able to test it. But it looks pretty much as if the theme would completely replace the WordPress editor. It does therefore not surprise me, that the plugin is not compatible with this theme.

However, you can still add the shortcode manually:
```
[donation_form language="en" one_time_1="10" one_time_2="20" one_time_3="50" one_time_4="100" recurring_1="5" recurring_2="10" recurring_3="30" recurring_4="100"]
```

Make sure you set the correct values: `language` should probabely be `de` in your case. The `one_time_X` values are the predefined amounts of one time donations, `recurring_X` the amounts of recurring donations. `one_time_X` and `recurring_X` are optional and may therefore be omitted.

**Comment by cyrillbolliger** [comment]
I'm closing this issue, as we're not planning to add support for the Divi theme.
